//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("CustomersModel", "FK_Order_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Customers_DataAccess.Customer), "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Customers_DataAccess.Order), true)]
[assembly: EdmRelationshipAttribute("CustomersModel", "FK_Orderitem_Order", "Order", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Customers_DataAccess.Order), "Order_item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Customers_DataAccess.Order_item), true)]
[assembly: EdmRelationshipAttribute("CustomersModel", "FK_Order_item_Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Customers_DataAccess.Product), "Order_item", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Customers_DataAccess.Order_item), true)]

#endregion

namespace Customers_DataAccess
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class CustomersEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new CustomersEntities object using the connection string found in the 'CustomersEntities' section of the application configuration file.
        /// </summary>
        public CustomersEntities() : base("name=CustomersEntities", "CustomersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomersEntities object.
        /// </summary>
        public CustomersEntities(string connectionString) : base(connectionString, "CustomersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new CustomersEntities object.
        /// </summary>
        public CustomersEntities(EntityConnection connection) : base(connection, "CustomersEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order> Orders
        {
            get
            {
                if ((_Orders == null))
                {
                    _Orders = base.CreateObjectSet<Order>("Orders");
                }
                return _Orders;
            }
        }
        private ObjectSet<Order> _Orders;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Order_item> Order_item
        {
            get
            {
                if ((_Order_item == null))
                {
                    _Order_item = base.CreateObjectSet<Order_item>("Order_item");
                }
                return _Order_item;
            }
        }
        private ObjectSet<Order_item> _Order_item;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Orders EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Order_item EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToOrder_item(Order_item order_item)
        {
            base.AddObject("Order_item", order_item);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomersModel", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="customerID">Initial value of the CustomerID property.</param>
        /// <param name="last_name">Initial value of the last_name property.</param>
        /// <param name="first_name">Initial value of the first_name property.</param>
        public static Customer CreateCustomer(global::System.Int32 customerID, global::System.String last_name, global::System.String first_name)
        {
            Customer customer = new Customer();
            customer.CustomerID = customerID;
            customer.last_name = last_name;
            customer.first_name = first_name;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CustomerID
        {
            get
            {
                return _CustomerID;
            }
            set
            {
                if (_CustomerID != value)
                {
                    OnCustomerIDChanging(value);
                    ReportPropertyChanging("CustomerID");
                    _CustomerID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CustomerID");
                    OnCustomerIDChanged();
                }
            }
        }
        private global::System.Int32 _CustomerID;
        partial void OnCustomerIDChanging(global::System.Int32 value);
        partial void OnCustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address_1
        {
            get
            {
                return _address_1;
            }
            set
            {
                Onaddress_1Changing(value);
                ReportPropertyChanging("address_1");
                _address_1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address_1");
                Onaddress_1Changed();
            }
        }
        private global::System.String _address_1;
        partial void Onaddress_1Changing(global::System.String value);
        partial void Onaddress_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String address_2
        {
            get
            {
                return _address_2;
            }
            set
            {
                Onaddress_2Changing(value);
                ReportPropertyChanging("address_2");
                _address_2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("address_2");
                Onaddress_2Changed();
            }
        }
        private global::System.String _address_2;
        partial void Onaddress_2Changing(global::System.String value);
        partial void Onaddress_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zip
        {
            get
            {
                return _Zip;
            }
            set
            {
                OnZipChanging(value);
                ReportPropertyChanging("Zip");
                _Zip = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zip");
                OnZipChanged();
            }
        }
        private global::System.String _Zip;
        partial void OnZipChanging(global::System.String value);
        partial void OnZipChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String phone
        {
            get
            {
                return _phone;
            }
            set
            {
                OnphoneChanging(value);
                ReportPropertyChanging("phone");
                _phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("phone");
                OnphoneChanged();
            }
        }
        private global::System.String _phone;
        partial void OnphoneChanging(global::System.String value);
        partial void OnphoneChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CustomersModel", "FK_Order_Customer", "Order")]
        public EntityCollection<Order> Orders
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order>("CustomersModel.FK_Order_Customer", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order>("CustomersModel.FK_Order_Customer", "Order", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomersModel", Name="Order")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="order_number">Initial value of the order_number property.</param>
        /// <param name="customerID">Initial value of the customerID property.</param>
        public static Order CreateOrder(global::System.Int32 order_number, global::System.Int32 customerID)
        {
            Order order = new Order();
            order.order_number = order_number;
            order.customerID = customerID;
            return order;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 order_number
        {
            get
            {
                return _order_number;
            }
            set
            {
                if (_order_number != value)
                {
                    Onorder_numberChanging(value);
                    ReportPropertyChanging("order_number");
                    _order_number = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("order_number");
                    Onorder_numberChanged();
                }
            }
        }
        private global::System.Int32 _order_number;
        partial void Onorder_numberChanging(global::System.Int32 value);
        partial void Onorder_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 customerID
        {
            get
            {
                return _customerID;
            }
            set
            {
                OncustomerIDChanging(value);
                ReportPropertyChanging("customerID");
                _customerID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("customerID");
                OncustomerIDChanged();
            }
        }
        private global::System.Int32 _customerID;
        partial void OncustomerIDChanging(global::System.Int32 value);
        partial void OncustomerIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> date_ordered
        {
            get
            {
                return _date_ordered;
            }
            set
            {
                Ondate_orderedChanging(value);
                ReportPropertyChanging("date_ordered");
                _date_ordered = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date_ordered");
                Ondate_orderedChanged();
            }
        }
        private Nullable<global::System.DateTime> _date_ordered;
        partial void Ondate_orderedChanging(Nullable<global::System.DateTime> value);
        partial void Ondate_orderedChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CustomersModel", "FK_Order_Customer", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("CustomersModel.FK_Order_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("CustomersModel.FK_Order_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("CustomersModel.FK_Order_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("CustomersModel.FK_Order_Customer", "Customer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CustomersModel", "FK_Orderitem_Order", "Order_item")]
        public EntityCollection<Order_item> Order_item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order_item>("CustomersModel.FK_Orderitem_Order", "Order_item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order_item>("CustomersModel.FK_Orderitem_Order", "Order_item", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomersModel", Name="Order_item")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Order_item : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Order_item object.
        /// </summary>
        /// <param name="item_id">Initial value of the item_id property.</param>
        /// <param name="order_number">Initial value of the order_number property.</param>
        /// <param name="product_desc">Initial value of the product_desc property.</param>
        /// <param name="quantity">Initial value of the quantity property.</param>
        public static Order_item CreateOrder_item(global::System.Int32 item_id, global::System.Int32 order_number, global::System.String product_desc, global::System.Int32 quantity)
        {
            Order_item order_item = new Order_item();
            order_item.item_id = item_id;
            order_item.order_number = order_number;
            order_item.product_desc = product_desc;
            order_item.quantity = quantity;
            return order_item;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 item_id
        {
            get
            {
                return _item_id;
            }
            set
            {
                if (_item_id != value)
                {
                    Onitem_idChanging(value);
                    ReportPropertyChanging("item_id");
                    _item_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("item_id");
                    Onitem_idChanged();
                }
            }
        }
        private global::System.Int32 _item_id;
        partial void Onitem_idChanging(global::System.Int32 value);
        partial void Onitem_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 order_number
        {
            get
            {
                return _order_number;
            }
            set
            {
                Onorder_numberChanging(value);
                ReportPropertyChanging("order_number");
                _order_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("order_number");
                Onorder_numberChanged();
            }
        }
        private global::System.Int32 _order_number;
        partial void Onorder_numberChanging(global::System.Int32 value);
        partial void Onorder_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                Onproduct_idChanging(value);
                ReportPropertyChanging("product_id");
                _product_id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("product_id");
                Onproduct_idChanged();
            }
        }
        private global::System.String _product_id;
        partial void Onproduct_idChanging(global::System.String value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String product_desc
        {
            get
            {
                return _product_desc;
            }
            set
            {
                Onproduct_descChanging(value);
                ReportPropertyChanging("product_desc");
                _product_desc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("product_desc");
                Onproduct_descChanged();
            }
        }
        private global::System.String _product_desc;
        partial void Onproduct_descChanging(global::System.String value);
        partial void Onproduct_descChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 quantity
        {
            get
            {
                return _quantity;
            }
            set
            {
                OnquantityChanging(value);
                ReportPropertyChanging("quantity");
                _quantity = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("quantity");
                OnquantityChanged();
            }
        }
        private global::System.Int32 _quantity;
        partial void OnquantityChanging(global::System.Int32 value);
        partial void OnquantityChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CustomersModel", "FK_Orderitem_Order", "Order")]
        public Order Order
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("CustomersModel.FK_Orderitem_Order", "Order").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("CustomersModel.FK_Orderitem_Order", "Order").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Order> OrderReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Order>("CustomersModel.FK_Orderitem_Order", "Order");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Order>("CustomersModel.FK_Orderitem_Order", "Order", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CustomersModel", "FK_Order_item_Product", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("CustomersModel.FK_Order_item_Product", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("CustomersModel.FK_Order_item_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("CustomersModel.FK_Order_item_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("CustomersModel.FK_Order_item_Product", "Product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CustomersModel", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="product_id">Initial value of the product_id property.</param>
        /// <param name="product_description">Initial value of the product_description property.</param>
        public static Product CreateProduct(global::System.String product_id, global::System.String product_description)
        {
            Product product = new Product();
            product.product_id = product_id;
            product.product_description = product_description;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String product_id
        {
            get
            {
                return _product_id;
            }
            set
            {
                if (_product_id != value)
                {
                    Onproduct_idChanging(value);
                    ReportPropertyChanging("product_id");
                    _product_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("product_id");
                    Onproduct_idChanged();
                }
            }
        }
        private global::System.String _product_id;
        partial void Onproduct_idChanging(global::System.String value);
        partial void Onproduct_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String product_description
        {
            get
            {
                return _product_description;
            }
            set
            {
                Onproduct_descriptionChanging(value);
                ReportPropertyChanging("product_description");
                _product_description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("product_description");
                Onproduct_descriptionChanged();
            }
        }
        private global::System.String _product_description;
        partial void Onproduct_descriptionChanging(global::System.String value);
        partial void Onproduct_descriptionChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CustomersModel", "FK_Order_item_Product", "Order_item")]
        public EntityCollection<Order_item> Order_item
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Order_item>("CustomersModel.FK_Order_item_Product", "Order_item");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Order_item>("CustomersModel.FK_Order_item_Product", "Order_item", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
